# reference: http://www.objc.io/issue-6/travis-ci.html

language: objective-c
install:
  - gem install cocoapods
  - cd Example && pod install && cd -
script:
  - xcodebuild -workspace Example/CloudantQueryObjc.xcworkspace -scheme 'CloudantQueryObjc' -destination 'platform=iOS Simulator,OS=8.0,name=iPhone 4S' build test
