# reference: http://www.objc.io/issue-6/travis-ci.html

language: objective-c
install:
  - gem install cocoapods
  - cd Example && pod install && cd -
script:
  - xctool test -workspace Example/CloudantQueryObjc.xcworkspace -scheme CloudantQueryObjc -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO
